version: "2"

services:
    goodhelp_nginx:
      ports:
        - "80:80"
        - 443:443
      build:
        args:
          env: prod
      volumes:
        - /var/log/nginx:/var/log/nginx/
        - /etc/nginx/ssl:/etc/nginx/ssl
      restart: always

    goodhelp_php_fpm:
      build:
        args:
          env: prod
      volumes:
         - ~/.composer/docker-cache/:/root/.composer:cached
         - ../../:/application

    goodhelp_redis:
      ports:
        - '7379:6379'

networks:
  default:
    external:
      name: goodhelp-network