sentry:
    dsn: '%env(SENTRY_DSN)%'
    register_error_listener: false # Disables the ErrorListener to avoid duplicated log in sentry

monolog:
    handlers:
        sentry:
            type: fingers_crossed
            action_level: error
            handler: sentry_main
            excluded_http_codes: [ 404, 405, 403 ]
            buffer_size: 50
        sentry_main:
            type: sentry
            level: error
            hub_id: Sentry\State\HubInterface